const teams = [
  { abbreviation: 'Atl', city: 'Atlanta', teamName: 'Falcons' },
  { abbreviation: 'Ari', city: 'Arizona', teamName: 'Cardinals' },
  { abbreviation: 'Bal', city: 'Baltimore', teamName: 'Ravens' },
  { abbreviation: 'Buf', city: 'Buffalo', teamName: 'Bills' },
  { abbreviation: 'Car', city: 'Carolina', teamName: 'Panthers' },
  { abbreviation: 'Chi', city: 'Chicago', teamName: 'Bears' },
  { abbreviation: 'Cin', city: 'Cincinnati', teamName: 'Bengals' },
  { abbreviation: 'Cle', city: 'Cleveland', teamName: 'Browns' },
  { abbreviation: 'Dal', city: 'Dallas', teamName: 'Cowboys' },
  { abbreviation: 'Den', city: 'Denver', teamName: 'Broncos' },
  { abbreviation: 'Det', city: 'Detroit', teamName: 'Lions' },
  { abbreviation: 'FA', city: 'Free Agency', teamName: 'N/A' },
  { abbreviation: 'Gb', city: 'Greenbay', teamName: 'Packers' },
  { abbreviation: 'Hou', city: 'Houston', teamName: 'Texans' },
  { abbreviation: 'Ind', city: 'Indianapolis', teamName: 'Colts' },
  { abbreviation: 'Jax', city: 'Jacksonville', teamName: 'Jaguars' },
  { abbreviation: 'KC', city: 'Kansas City', teamName: 'Chiefs' },
  { abbreviation: 'LA', city: 'Los Angeles', teamName: 'Rams' },
  { abbreviation: 'Mia', city: 'Miami', teamName: 'Dolphins' },
  { abbreviation: 'Min', city: 'Minnesota', teamName: 'Vikings' },
  { abbreviation: 'NE', city: 'New England', teamName: 'Patriots' },
  { abbreviation: 'NO', city: 'New Orleans', teamName: 'Saints' },
  { abbreviation: 'NYG', city: 'New York Giants', teamName: 'Giants' },
  { abbreviation: 'NYJ', city: 'New York Jets', teamName: 'Jets' },
  { abbreviation: 'Oak', city: 'Oakland', teamName: 'Radiers' },
  { abbreviation: 'Phi', city: 'Philadelphia', teamName: 'Eagles' },
  { abbreviation: 'Pit', city: 'Pittsburgh', teamName: 'Steelers' },
  { abbreviation: 'SD', city: 'San Diego', teamName: 'Chargers' },
  { abbreviation: 'Sea', city: 'Seattle', teamName: 'Seahawks' },
  { abbreviation: 'SF', city: 'San Francisco', teamName: '49ers' },
  { abbreviation: 'TB', city: 'Tampa Bay', teamName: 'Buccaneers' },
  { abbreviation: 'Ten', city: 'Tennessee', teamName: 'Titans' },
  { abbreviation: 'Wsh', city: 'Washington', teamName: 'Redskins' }
];

module.exports = teams;
