const teams = {
  'Ari': { teamId: 1,city: 'Arizona', teamName: 'Cardinals' },
  'Atl': { teamId: 2, city: 'Atlanta', teamName: 'Falcons' },
  'Bal': { teamId: 3, city: 'Baltimore', teamName: 'Ravens' },
  'Buf': { teamId: 4, city: 'Buffalo', teamName: 'Bills' },
  'Car': { teamId: 5, city: 'Carolina', teamName: 'Panthers' },
  'Chi': { teamId: 6, city: 'Chicago', teamName: 'Bears' },
  'Cin': { teamId: 7, city: 'Cincinnati', teamName: 'Bengals' },
  'Cle': { teamId: 8, city: 'Cleveland', teamName: 'Browns' },
  'Dal': { teamId: 9, city: 'Dallas', teamName: 'Cowboys' },
  'Den': { teamId: 10, city: 'Denver', teamName: 'Broncos' },
  'Det': { teamId: 11, city: 'Detroit', teamName: 'Lions' },
  'FA': { teamId: 12, city: 'Free Agency', teamName: 'N/A' },
  'GB': { teamId: 13, city: 'Greenbay', teamName: 'Packers' },
  'Hou': { teamId: 14, city: 'Houston', teamName: 'Texans' },
  'Ind': { teamId: 15, city: 'Indianapolis', teamName: 'Colts' },
  'Jax': { teamId: 16, city: 'Jacksonville', teamName: 'Jaguars' },
  'KC': { teamId: 17, city: 'Kansas teamId: City', teamName: 'Chiefs' },
  'LA': { teamId: 18, city: 'Los Angeles', teamName: 'Rams' },
  'Mia': { teamId: 19, city: 'Miami', teamName: 'Dolphins' },
  'Min': { teamId: 20, city: 'Minnesota', teamName: 'Vikings' },
  'NE': { teamId: 21, city: 'New England', teamName: 'Patriots' },
  'NO': { teamId: 22, city: 'New Orleans', teamName: 'Saints' },
  'NYG': { teamId: 23, city: 'New York Giants', teamName: 'Giants' },
  'NYJ': { teamId: 24, city: 'New York Jets', teamName: 'Jets' },
  'Oak': { teamId: 25, city: 'Oakland', teamName: 'Radiers' },
  'Phi': { teamId: 26, city: 'Philadelphia', teamName: 'Eagles' },
  'Pit': { teamId: 27, city: 'Pittsburgh', teamName: 'Steelers' },
  'SD': { teamId: 28, city: 'San Diego', teamName: 'Chargers' },
  'Sea': { teamId: 29, city: 'Seattle', teamName: 'Seahawks' },
  'SF': { teamId: 30, city: 'San Francisco', teamName: '49ers' },
  'TB': { teamId: 31, city: 'Tampa Bay', teamName: 'Buccaneers' },
  'Ten': { teamId: 32, city: 'Tennessee', teamName: 'Titans' },
  'Wsh': { teamId: 33, city: 'Washington', teamName: 'Redskins' }
};

module.exports = teams;
